### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by jensens** [collective/Products.ContentWellPortlets#3]
there happend a bunch of important changes lately, may we have a release?

**Comment by thet** [comment]
notification to: @esteele @cah190 @RobZoneNet @pumazi

**Comment by jensens** [comment]
or just give one of us pypi access :)

**Comment by cah190** [comment]
I'll take a look and likely make a release today.

**Comment by cah190** [comment]
4.3.0 is released.

**Comment by jensens** [comment]
1000 thanks!
