### ISSUE TITLE
Error installing in Plone 5

### ISSUE THREAD

**Issue by adamc-be** [collective/Products.ContentWellPortlets#4]
LICENCE.txt says:

= Prerequisites =
Plone 4.0 or higher

However, when trying to install in Plone 5, from  /<portal>/prefs_install_products_form, it fails with this error:

> Traceback (innermost last):
>   Module ZPublisher.Publish, line 146, in publish
>   Module Zope2.App.startup, line 301, in commit
>   Module transaction._manager, line 89, in commit
>   Module transaction._transaction, line 329, in commit
>   Module transaction._transaction, line 443, in _commitResources
>   Module ZODB.Connection, line 567, in commit
>   Module ZODB.Connection, line 623, in _commit
>   Module ZODB.Connection, line 658, in _store_objects
>   Module ZODB.serialize, line 422, in serialize
>   Module ZODB.serialize, line 431, in _dump
> PicklingError: Can't pickle <class 'collective.panels.interfaces.ILayer'>: import of module collective.panels.interfaces failed

**Comment by miohtama** [comment]
I guess this addon has not been updated to Plone 5 as it came out only couple of weeks ago. Check commit log and branches on Github to see if anybody has been working on the P5 compatibility.

**Comment by adamc-be** [comment]
1 branch (main), no pull requests and no commit activity in the last month.
Doesn't look like anything will be available soon.
Looks like this might be a good way for me to learn about Plone add-ons!

**Comment by witekdev** [comment]
@adamc-be I am currently testing this in Plone 5 (5.0.4) and with the exception of some hiccups in the toolbar, I am able to add and remove portlets in the various portletmanagers that this add-on provides, so I would regard it to be working, but needs some polish.

**Comment by witekdev** [comment]
@cah190 @RobZoneNet
I see you guys are one of the package owners on pypi:
https://pypi.python.org/pypi/Products.ContentWellPortlets

Could one of you perhaps update the classifier that this is product is Plone5 compatible and maybe cut a new release? Thanks!

**Comment by adamc-be** [comment]
@witekdev 
Our project has moved on a bit now, and we are probably not going to be using Plone :-(
Still, it looks like you've fixed the issue I highlighted, so yes, I think it should be closed.
Thanks for your time!
