### ISSUE TITLE
Plone5 - when this product is installed, the plone toolbar manage portlets section, displays nothing when expanded

### ISSUE THREAD

**Issue by witekdev** [collective/Products.ContentWellPortlets#6]
![screenshot from 2016-04-06 11 55 14](https://cloud.githubusercontent.com/assets/883619/14325522/538ae8b6-fbef-11e5-8248-e4f652d07a94.jpg)

This is due to the number of portlet managers that this product adds to the system (30):
plone.app.contentmenu.menu.py lines 871-906

Not sure how to proceed, and if this is an issue that should rather be filled under Products.CMFPlone bugs rather?

**Comment by witekdev** [comment]
Related to:
https://github.com/plone/Products.CMFPlone/issues/1266

**Comment by ezvirtual** [comment]
It appears that the manage portlet menu does exist, it's just hidden from view with a huge margin pushing it off the top of the page:
`element {
    margin-top: -1214px;
}`

**Comment by witekdev** [comment]
@ezvirtual thanks for the feedback.
